services:
  db:
    image: postgres:trixie
    container_name: todo-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - todo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: todo-app
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${APP_PORT}
volumes:
  todo-db-data: